# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: apex_manifest.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13\x61pex_manifest.proto\x12\napex.proto\"\xf9\x03\n\x0c\x41pexManifest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0f\n\x07version\x18\x02 \x01(\x03\x12\x16\n\x0epreInstallHook\x18\x03 \x01(\t\x12\x1b\n\x0fpostInstallHook\x18\x04 \x01(\tB\x02\x18\x01\x12\x13\n\x0bversionName\x18\x05 \x01(\t\x12\x0e\n\x06noCode\x18\x06 \x01(\x08\x12\x19\n\x11provideNativeLibs\x18\x07 \x03(\t\x12\x19\n\x11requireNativeLibs\x18\x08 \x03(\t\x12\x0f\n\x07jniLibs\x18\t \x03(\t\x12!\n\x15requireSharedApexLibs\x18\n \x03(\tB\x02\x18\x01\x12!\n\x15provideSharedApexLibs\x18\x0b \x01(\x08\x42\x02\x18\x01\x12\x46\n\rcapexMetadata\x18\x0c \x01(\x0b\x32/.apex.proto.ApexManifest.CompressedApexMetadata\x12 \n\x18supportsRebootlessUpdate\x18\r \x01(\x08\x12\x13\n\x0bvndkVersion\x18\x0e \x01(\t\x12\x1b\n\x0fvendorBootstrap\x18\x0f \x01(\x08\x42\x02\x18\x01\x12\x11\n\tbootstrap\x18\x10 \x01(\x08\x1a\x34\n\x16\x43ompressedApexMetadata\x12\x1a\n\x12originalApexDigest\x18\x01 \x01(\tB\x1a\n\x10\x63om.android.apexB\x06Protosb\x06proto3')



_APEXMANIFEST = DESCRIPTOR.message_types_by_name['ApexManifest']
_APEXMANIFEST_COMPRESSEDAPEXMETADATA = _APEXMANIFEST.nested_types_by_name['CompressedApexMetadata']
ApexManifest = _reflection.GeneratedProtocolMessageType('ApexManifest', (_message.Message,), {

  'CompressedApexMetadata' : _reflection.GeneratedProtocolMessageType('CompressedApexMetadata', (_message.Message,), {
    'DESCRIPTOR' : _APEXMANIFEST_COMPRESSEDAPEXMETADATA,
    '__module__' : 'apex_manifest_pb2'
    # @@protoc_insertion_point(class_scope:apex.proto.ApexManifest.CompressedApexMetadata)
    })
  ,
  'DESCRIPTOR' : _APEXMANIFEST,
  '__module__' : 'apex_manifest_pb2'
  # @@protoc_insertion_point(class_scope:apex.proto.ApexManifest)
  })
_sym_db.RegisterMessage(ApexManifest)
_sym_db.RegisterMessage(ApexManifest.CompressedApexMetadata)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\020com.android.apexB\006Protos'
  _APEXMANIFEST.fields_by_name['postInstallHook']._options = None
  _APEXMANIFEST.fields_by_name['postInstallHook']._serialized_options = b'\030\001'
  _APEXMANIFEST.fields_by_name['requireSharedApexLibs']._options = None
  _APEXMANIFEST.fields_by_name['requireSharedApexLibs']._serialized_options = b'\030\001'
  _APEXMANIFEST.fields_by_name['provideSharedApexLibs']._options = None
  _APEXMANIFEST.fields_by_name['provideSharedApexLibs']._serialized_options = b'\030\001'
  _APEXMANIFEST.fields_by_name['vendorBootstrap']._options = None
  _APEXMANIFEST.fields_by_name['vendorBootstrap']._serialized_options = b'\030\001'
  _APEXMANIFEST._serialized_start=36
  _APEXMANIFEST._serialized_end=541
  _APEXMANIFEST_COMPRESSEDAPEXMETADATA._serialized_start=489
  _APEXMANIFEST_COMPRESSEDAPEXMETADATA._serialized_end=541
# @@protoc_insertion_point(module_scope)
